### ISSUE TITLE
Pseudo selectors recommendation, especially disabled

### ISSUE THREAD

**Issue by adrianbota** [getbem/getbem.com#131]
I couldn't find a recommendation for using state pseudo selectors like `:hover`, `:active`, `:focus` and, most important, `:disabled`.

What would be the recommended way to write styles for a disabled state of a `<button>` element and also make it available for an `<a>` element that doesn't support it, keeping in mind that `:disabled` also prevents click and focus which can't be controlled from css.

In the classic way you would write:

```
.btn:disabled,
.btn.disabled {
    /* styles here */
}

a.btn.disabled {
    pointer-events: none;
}
```

I understand making making a link disabled is not a common or recommended pattern, but it may happen in the real world. How you you write that in the BEM world?

Thank you

**Comment by adrianbota** [comment]
Also `:checked` state is a good candidate, where you want to leverage pure CSS state and combine it with `+` to style adjacent elements. I BEM world you might want to toggle a class as well and that forces you to use javascript.

**Comment by iamdey** [comment]
I think pseudo selectors and classes don't have the same meaning and not the same purpose (also, it might not be synced).

So I would write:

```
.btn {
  &:disabled {
    //... depends of dom state
  }
  &--disabled {
    //... depends on application state
  }
}
```

**Comment by adrianbota** [comment]
Thanks @iamdey, makes sense. Any suggestion on using `:checked` with adjacent selector (+) ?

**Comment by iamdey** [comment]
It's sounds related to #102 and the article linked says something like "it's still CSS, do the F* you want" (but I am not enough awake to think about it)

Well my though is, if you follow ITCSS ideas and you apply it to a very specific part of the site/app, it might not be a problem.

I think it's the same argument, in case my case I would prefer to use the old (and verbose) solution using javascript (mostly because I know more js than css :p)

I suppose you want a `label` with a "state" related to your checkbox, the label modifier is defined following  the state of the app besides the checkbox set the state of the app:

```
.form-group {
  &__checkbox:checked {
    // ...
  }
  &__label--enabled {
    // ...
  }
}
```

**Comment by adrianbota** [comment]
Thank you!
